name: Deploy to Staging Server
on:
  push:
    branches: [stage]

jobs:
  deploy:
    name: Deploying to Stage Server
    runs-on: [ self-hosted, lex-stage-vm ]
    environment: stage
    env:
      CONTAINER_NAME: Lex-Server-Stage
      IMAGE_NAME_TAG: lex-server-stage:latest
      HOST_PORT: 3001
      CONTAINER_PORT: 3001

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          clean: False
      
      - name: Building and Assigning Tag to image
        run: |
          docker build -t $IMAGE_NAME_TAG .
      
      - name: Removing old Container if exits
        run: |
          docker stop $CONTAINER_NAME || true && docker rm $CONTAINER_NAME || true
      
      - name: Starting Docker Container
        run: |
          docker run -d -p $HOST_PORT:$CONTAINER_PORT --restart unless-stopped --name $CONTAINER_NAME  $IMAGE_NAME_TAG
      
      - name: View Docker status
        run: |
          docker ps
      
      - name: Cleaning Server
        run: |
          echo y | docker system prune -a

